kind: pipeline
name: default
type: docker

steps:

    - name: test
      image: python:3.7-buster
      commands:
          - pip install -qr requirements.txt
          - pytest -x --cov --cov-report xml

services:
  - name: mongo
    image: mongo:4.4
    command: [--nojournal]
    ports:
      - 27017