name: virtool_cli

on:
  pull_request:
    branches: [ master ]
  push:
    branches: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run CI
        run: docker-compose up --build --abort-on-container-exit --exit-code-from pytest

      - name: Run codacy-coverage-reporter
        if: ${{ github.event_name == 'push' }}
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: $GITHUB_WORKSPACE/coverage.xml
